# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: FrigateSender
version: "1.2.0"
slug: frigatesender
description: Sends Frigate snapshots and videos without needing to expose anything to the internet.
url: "https://github.com/InfriaAB/FrigateSender"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"