# Example frigate sender configuration.

# Snapshot rate limit interval per camera in seconds.
rateLimitTimeout: 10

# Max file (video) size per upload, files larger than this will be split apart.
# This depends on the service you are using, Telegram has max limit of 50Mb per file.
fileSizeMaxPerSend: 48

# Base URL of Home Assistant
baseURL: https://homeassistant.local:8123

# Frigate URL in HomeAssistant for Snapshots.
snapShotURL: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?quality=90&bbox=1'

# Frigate URL in HomeAssistant for Videos.
videoURL: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'

# Time to wait in seconds after receiving Frigate "end" event before trying to get video from the API.
# Frigate takes time to store videos, when getting to soon only a partial download will be made.
# If you are not getting comeplete videos increase this in increments of 10.
frigateVideoSendDelay: 25

# Where to store log files.
loggingPath: logs

# Temporary folder for storing media files.
temporaryFolder: temp

# What level of logging to do.
# 10 = Debug, 20 = Info. Debug = more spam and details.
loggingLevel: 10

# MQTT Adress that is being used by Frigate (probably same as Home Assistant).
mQTTAddress: homeassistant.local

# MQTT Port.
mQTTPort: 1883

#  Timeout tolerance
mQTTTimeout: 60

# MQTT User
mQTTUser: homeassistant

#  MQTT Password
mQTTPassword: password

# MQTT Topic for Frigate events.
mQTTTopic: frigate/events

# Telegram Chat bot token
telegramToken: telegram-bot-token

# Telegram chat to send to.
telegramChatId: -123

# Telegram chat to send videos to, can be same as TelegramChatId.
# If a lot of videos are generated it could be nice to  have this in a 
# separate muted chat and just have notifications on the snapshot chat.
telegramVideoChatId: -456