rateLimitTimeout: 20
rateLimit: 6
fileSizeMaxPerSend: 48
baseURL: https://homeassistant.local:8123
snapShotURL: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?quality=90&bbox=1'
videoURL: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
frigateVideoSendDelay: 25
loggingPath: logs
temporaryFolder: temp
loggingLevel: 10
mQTTAddress: homeassistant.local
mQTTPort: 1883
mQTTTimeout: 60
mQTTUser: homeassistant
mQTTPassword: nee3mequohf0soh1euTh8ophoPh1AeHee0aeng5chouv2ohj6ohv0aenaequah9e
mQTTTopic: frigate/events
telegramToken: 6088531760:AAEbDsM03Rp4ug0UkelcK1GSGW6wDtSkYAw
telegramChatId: -922271985
