rateLimitTimeout: 20
rateLimit: 6
fileSizeMaxPerSend: 48
baseURL: https://homeassistant.local:8123
snapShotURL: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?quality=90&bbox=1'
videoURL: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
loggingPath: logs
loggingLevel: 10
mQTTAddress: homeassistant.local
mQTTPort: 1883
mQTTTimeout: 60
mQTTUser: user
mQTTPassword: password
mQTTTopic: frigate/events
telegramToken: 123:1234
telegramChatId: -123
